name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write # This is important - gives the workflow permission to write to the repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Change this to 'build' if your project uses Create React App
          branch: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}  # This is automatically provided by GitHub
          clean: true  # Automatically removes deleted files from the deploy branch
